import test from 'node:test';
import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { BilibiliClient, mediaUrls, signWbi } from '../src/main/modules/bilibiliClient';
const image='https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png';
const sub='https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png';
function fake(routes:Record<string,any>,calls:URL[]=[]){return new BilibiliClient(async(raw,init)=>{const u=new URL(raw);calls.push(u);assert.equal(init.headers.Referer,'https://www.bilibili.com/');const data=routes[u.pathname];if(data===undefined) throw new Error('unexpected request');return Response.json({code:0,data:typeof data==='function'?data(u):data});});}
const base={
  '/x/web-interface/nav':{isLogin:true,mid:42,uname:'测试用户',wbi_img:{img_url:image,sub_url:sub}},
  '/x/v3/fav/folder/created/list-all':{count:2,list:[{id:1},{id:2}]},
  '/x/v3/fav/resource/list':(u:URL)=>u.searchParams.get('media_id')==='1'?{medias:[]}:{info:{title:'音乐'},medias:[{type:2,bvid:'BVfirst',title:'第一首'},{type:2,bvid:'BVsecond'}]},
  '/x/web-interface/view':{title:'歌名',pages:[{cid:101},{cid:102}]},
  '/x/player/wbi/playurl':{dash:{audio:[{codecs:'mp4a.40.2',bandwidth:64000,baseUrl:'https://cdn.bilivideo.com/low'},{codecs:'mp4a.40.2',bandwidth:128000,baseUrl:'https://cdn.bilivideo.com/high',backupUrl:['https://backup.bilivideo.com/high']}],dolby:{audio:[{codecs:'ec-3',bandwidth:999999,baseUrl:'https://cdn.bilivideo.com/dolby'}]}}}
};
test('WBI known key matches Python urlencode signature',()=>{const query='bar=123&foo=a+b&wts=1702204169';const expected=createHash('md5').update(query+'ea1db124af3c7062474693fa704f4ff8').digest('hex');assert.equal(signWbi({foo:"a!'()* b",bar:123},image,sub,1702204169),query+'&w_rid='+expected);});
test('WBI strips forbidden characters and escapes Unicode/spaces',()=>{const s=signWbi({name:"中文 !'()*"},image,sub,1);assert.match(s,/name=%E4%B8%AD%E6%96%87\+/);assert.doesNotMatch(s,/[!'()*]/);assert.throws(()=>signWbi({},'https://x/a.png',sub),/key/);});
test('full favorite flow skips empty folder, uses first video first P and best AAC',async()=>{const calls:URL[]=[];const result=await fake(base,calls).favorite();assert.equal(result.title,'歌名');assert.equal(result.cid,101);assert.equal(result.bvid,'BVfirst');assert.equal(result.urls[0],'https://cdn.bilivideo.com/high');const play=calls.find(u=>u.pathname.endsWith('playurl'))!;assert.equal(play.searchParams.get('cid'),'101');assert.ok(play.searchParams.has('w_rid'));assert.equal(calls.find(u=>u.pathname.endsWith('/view'))!.searchParams.get('bvid'),'BVfirst');});
test('explicit folder skips automatic folder lookup',async()=>{const calls:URL[]=[];await fake(base,calls).favorite(2);assert.ok(!calls.some(u=>u.pathname.endsWith('list-all')));});
test('incomplete folder list is paged in original order',async()=>{const calls:URL[]=[];const client=fake({...base,'/x/v3/fav/folder/created/list-all':{count:2,list:[{id:1}]},'/x/v3/fav/folder/created/list':(u:URL)=>u.searchParams.get('pn')==='1'?{list:[{id:1}],has_more:true}:{list:[{id:2}],has_more:false}},calls);assert.equal((await client.favorite()).bvid,'BVfirst');assert.equal(calls.filter(u=>u.pathname.endsWith('/created/list')).length,2);});
test('pagination cannot silently replace missing first folder',async()=>{await assert.rejects(fake({...base,'/x/v3/fav/folder/created/list-all':{count:2,list:[]},'/x/v3/fav/folder/created/list':{list:[],has_more:true}}).favorite(),/分页/);});
test('expired account, empty favorites, invalid video and missing first P fail visibly',async()=>{await assert.rejects(fake({...base,'/x/web-interface/nav':{isLogin:false}}).favorite(),/登录/);await assert.rejects(fake({...base,'/x/v3/fav/resource/list':{medias:[]}}).favorite(),/非空/);await assert.rejects(fake({...base,'/x/v3/fav/resource/list':{medias:[{type:12},{type:2,bvid:'BVsecond'}]}}).favorite(),/第一条/);await assert.rejects(fake({...base,'/x/web-interface/view':{pages:[]}}).favorite(),/第一/);});
test('missing WBI keys and absent AAC tracks fail without choosing another video',async()=>{await assert.rejects(fake({...base,'/x/web-interface/nav':{isLogin:true,mid:42}}).favorite(),/签名/);await assert.rejects(fake({...base,'/x/player/wbi/playurl':{dash:{audio:[]}}}).favorite(),/AAC/);});
test('QR generate/poll uses passport endpoint and preserves scan status',async()=>{const calls:URL[]=[];const client=fake({'/x/passport-login/web/qrcode/generate':{url:'https://passport.bilibili.com/login',qrcode_key:'key'},'/x/passport-login/web/qrcode/poll':{code:86090}},calls);assert.equal((await client.qr()).qrcode_key,'key');assert.equal((await client.poll('key')).code,86090);assert.equal(calls[1].hostname,'passport.bilibili.com');assert.equal(calls[1].searchParams.get('qrcode_key'),'key');});
test('reject network, HTTP, malformed JSON and nonzero API response without leaking URLs',async()=>{const secret='https://cdn.bilivideo.com/x?secret=hidden';await assert.rejects(new BilibiliClient(async()=>{throw new Error(secret);}).nav(),e=>!String(e).includes('hidden'));await assert.rejects(new BilibiliClient(async()=>new Response('',{status:403})).nav(),/403/);await assert.rejects(new BilibiliClient(async()=>new Response('bad json')).nav(),/格式/);await assert.rejects(new BilibiliClient(async()=>Response.json({code:-101})).nav(),/-101/);});
test('media URL allowlist, HTTPS and duplicate handling',()=>{assert.deepEqual(mediaUrls({base_url:'https://a.bilivideo.cn/a',backup_url:['https://a.bilivideo.cn/a','http://a.bilivideo.com/a','https://evil.test/a','https://bilivideo.com.evil.test/a','file:///tmp/a','https://a.akamaized.net/a']}),['https://a.bilivideo.cn/a','https://a.akamaized.net/a']);});
